### PR TITLE
Fix build on non-Linux platforms and allow baud rate to be set on the command line.

### PR DESCRIPTION
**Pull request by DanielO**
I built this on MacOSX and used it to talk to a Spartan 3 with a hacked up version of testbus.v via an FTDI USB UART.

### CODE REVIEW

**Comment by ZipCPU** [comment]
I like a lot of what you've done there, but ... have a puzzling question: why did you change the "static const int BAUDRATE" into a "#define" macro?  The first has type checking, the latter ... not so much.

Dan

**Comment by DanielO** [comment]
Mostly.. habit :) It also matched the other stuff in there (R_VERSION etc)

I avoid declaring variables in headers to avoid linker errors if you have the same header in 2 files linked toger (although in this case it would be OK since it is static).

The compiler will type check it when it's used so I think it's OK from that perspective.

That said, if you prefer it the other way I'm happy to update the diff.

**Comment by ZipCPU** [comment]
Ok, I'm finally getting a chance to look this over.  Some things I'm noticing:

1. The baud rate is set within the design.  It's captured in regdefs.h in a place usable for all modules using the design.  It should not be changed afterwards, lest other things depending upon change as well.
2. According to the man page for `cfsetspeed`, it's a BSD extension.  `cfgetispeed` and `cfgetospeed` are the standard means for adjusting the baud rate.
3. Also according to the man page, `cfispeed` must be given one of the `Bnnn` constants defined in the usr include file.  These may or may not match the actual speed chosen.

This leaves behind the issue of `POLLRDHUP`--which doesn't appear to be universally supported even on linux distributions, and  the "default" /ttyUSB filename component.

Dan

**Comment by ZipCPU** [comment]
Fixed in #3 .
Dan

**Pull request closed without merging**
